### PR TITLE
Added SparkSession configs statements if non-default namespace used

### PR DESCRIPTION
**Pull request by morooshka**
Added SparkSession configs statements if non-default namespace used to the demo notebook. Otherwise the SparkSession would not be created with an error referring to the wrong namespace

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you for this PR! We'll take a look at this in the next few days.

**Comment by maltesander** [comment]
Hi @morooshka,
thanks for your contribution :)

The PR looks good overall, i will try to test tomorrow.

We would like to keep the output (charts and tables) in the notebook though. This way you can e.g. see what the results look like e.g. via github as well or if anything goes wrong (e.g. like not enough memory etc.) during execution.

Im fine with you doing it, otherwise i can push the executed notebook again including your changes.

Cheers,
Malte

**Comment by morooshka** [comment]
> Hi @morooshka, thanks for your contribution :)
> The PR looks good overall, i will try to test tomorrow.
> We would like to keep the output (charts and tables) in the notebook though. This way you can e.g. see what the results look like e.g. via github as well or if anything goes wrong (e.g. like not enough memory etc.) during execution.
> Im fine with you doing it, otherwise i can push the executed notebook again including your changes.
> Cheers, Malte

OK, I'll repush it. I thought someone had forgotten to delete the outputs
Thanks for quick responce

**Comment by morooshka** [comment]
Hi @maltesander! I've repushed the notebook with outputs as requested

**Comment by maltesander** [comment]
Hey @morooshka, tested and works. Thank you!

One nitpick, there is one typo `deploynig` when defining the namespace (i cannot suggest via git due to large diff).
```
# Modify this please if using non-default product namespace for demo deploynig 
NAMESPACE: str = "default"
```
Otherwise we can merge :)

**Comment by morooshka** [comment]
> Hey @morooshka, tested and works. Thank you!
> One nitpick, there is one typo `deploynig` when defining the namespace (i cannot suggest via git due to large diff).

OMG, thank you for noticing it, I'll repush

**Comment by morooshka** [comment]
@maltesander I have repushed, thank you

**Review by maltesander — APPROVED** [review]
No worries and thank you, looks good to me :)

**Pull request merged**
