### PR TITLE
docs: Link to recording in e2e-security demo docs

### PR DESCRIPTION
**Pull request by sbernauer**

### CODE REVIEW

**Comment by fhennig** [comment]
Needs additional textual description of what's to see in the pics

**Comment by sbernauer** [comment]
They will follow at some point of time when I find the time... :/

**Review by stackfab — CHANGES_REQUESTED** [review]
docs/modules/demos/images/end-to-end-security/overview.svg

needs polishing prio to publication

**Comment by NickLarsenNZ** [comment]
> docs/modules/demos/images/end-to-end-security/overview.svg
> 
> needs polishing prio to publication

Any suggestions on what to polish? Eg:
- Color scheme,
- Boxes with rounded corneres,
- Legend using icons or colored text instead of colored background
- Dimensions/Aspect Ratio

**Comment by stackfab** [comment]
Use this: https://stackable.tech/wp-content/uploads/2024/05/end2endsecuritydemo.png

**Comment by sbernauer** [comment]
@stackfab I pulled the new version from the slides. I did however export the png from google slides directly as it has a much better resolution. I hope that's ok

**Comment by fhennig** [comment]
Could you add [alt text](https://docs.asciidoctor.org/asciidoc/latest/macros/images/) to the images please? :innocent:

**Review by stackfab — APPROVED** [review]

**Pull request merged**
