### PR TITLE
fix: Update Remote URLs in NiFi for fetching data

### PR DESCRIPTION
**Pull request by xeniape**
Fix for https://github.com/stackabletech/demos/issues/62
Also includes an updated screenshot for the documentation, which was showing errors in NiFi because of this.

### CODE REVIEW

**Review by NickLarsenNZ — CHANGES_REQUESTED** [review]
LGTM, just need to merge into the `next` branch.

**Comment by sbernauer** [comment]
IMHO it's better to merge into main to get the fix right now. There is no need to wait for SDP 24.11, as we are not using any new product versions or features of it

**Review by NickLarsenNZ — APPROVED** [review]
LGTM

**Comment by NickLarsenNZ** [comment]
> IMHO it's better to merge into main to get the fix right now. There is no need to wait for SDP 24.11, as we are not using any new product versions or features of it

I'll update the `next` branch once this is merged.

**Comment by sbernauer** [comment]
> I'll update the next branch once this is merged.

I though we are going to merge next into main eventually? Wouldn't this cause merge conflicts?

**Comment by sbernauer** [comment]
Ahh or merge main into next? That would make sense I guess

**Comment by NickLarsenNZ** [comment]
I'll cherry-pick this into the release-24.7 branch.

**Pull request merged**
